### ISSUE TITLE
Migrate to github actions

### ISSUE THREAD

**Issue by rvolosatovs** [TheThingsIndustries/protoc-gen-gogottn#1]
#### Summary

Migrate to gihub actions

#### Why do we need this?

https://github.com/TheThingsIndustries/infrastructure/issues/832

#### What is already there? What do you see now?

Travis

#### What is missing? What do you want to see?

Github actions

#### Environment

CI

#### How do you propose to implement this?

translate `.travis.yml` into a github action

#### Can you do this yourself and submit a Pull Request?

yes

**Comment by nejraselimovic** [comment]
@johanstokking @htdvisser I see you're tracking the issue of moving stuff to GitHub Actions in https://github.com/TheThingsIndustries/infrastructure/issues/832, so do you need this repository at all? What is it meant for?

**Comment by htdvisser** [comment]
I think we can close this issue. This repository will become obsolete when we migrate away from GoGo protobuf (https://github.com/TheThingsNetwork/lorawan-stack/issues/2798).
